// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: analytics.sql

package query

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countAnalyticsBouncedVisits = `-- name: CountAnalyticsBouncedVisits :one
SELECT count(*)::bigint AS total
FROM analytics_sessions
WHERE started_at >= $1 AND started_at < $2
  AND pageviews <= 1
`

type CountAnalyticsBouncedVisitsParams struct {
	StartedAt   time.Time `json:"started_at"`
	StartedAt_2 time.Time `json:"started_at_2"`
}

func (q *Queries) CountAnalyticsBouncedVisits(ctx context.Context, arg CountAnalyticsBouncedVisitsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countAnalyticsBouncedVisits, arg.StartedAt, arg.StartedAt_2)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const countAnalyticsViews = `-- name: CountAnalyticsViews :one
SELECT count(*)::bigint AS total
FROM analytics_pageviews
WHERE occurred_at >= $1 AND occurred_at < $2
`

type CountAnalyticsViewsParams struct {
	OccurredAt   time.Time `json:"occurred_at"`
	OccurredAt_2 time.Time `json:"occurred_at_2"`
}

func (q *Queries) CountAnalyticsViews(ctx context.Context, arg CountAnalyticsViewsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countAnalyticsViews, arg.OccurredAt, arg.OccurredAt_2)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const countAnalyticsVisitors = `-- name: CountAnalyticsVisitors :one
SELECT count(DISTINCT coalesce(visitor_id::text, session_key))::bigint AS total
FROM analytics_sessions
WHERE started_at >= $1 AND started_at < $2
`

type CountAnalyticsVisitorsParams struct {
	StartedAt   time.Time `json:"started_at"`
	StartedAt_2 time.Time `json:"started_at_2"`
}

func (q *Queries) CountAnalyticsVisitors(ctx context.Context, arg CountAnalyticsVisitorsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countAnalyticsVisitors, arg.StartedAt, arg.StartedAt_2)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const countAnalyticsVisits = `-- name: CountAnalyticsVisits :one
SELECT count(*)::bigint AS total
FROM analytics_sessions
WHERE started_at >= $1 AND started_at < $2
`

type CountAnalyticsVisitsParams struct {
	StartedAt   time.Time `json:"started_at"`
	StartedAt_2 time.Time `json:"started_at_2"`
}

func (q *Queries) CountAnalyticsVisits(ctx context.Context, arg CountAnalyticsVisitsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countAnalyticsVisits, arg.StartedAt, arg.StartedAt_2)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const createAnalyticsPageview = `-- name: CreateAnalyticsPageview :exec
INSERT INTO analytics_pageviews (
    session_id,
    visitor_id,
    path,
    title,
    referrer,
    referrer_host,
    channel,
    browser,
    os,
    device,
    country_code,
    region,
    city,
    timezone,
    language,
    occurred_at
)
VALUES (
    $1, $2, $3, $4, $5, $6, $7,
    $8, $9, $10, $11, $12, $13, $14, $15, $16
)
`

type CreateAnalyticsPageviewParams struct {
	SessionID    uuid.UUID   `json:"session_id"`
	VisitorID    pgtype.UUID `json:"visitor_id"`
	Path         string      `json:"path"`
	Title        string      `json:"title"`
	Referrer     string      `json:"referrer"`
	ReferrerHost string      `json:"referrer_host"`
	Channel      string      `json:"channel"`
	Browser      string      `json:"browser"`
	Os           string      `json:"os"`
	Device       string      `json:"device"`
	CountryCode  string      `json:"country_code"`
	Region       string      `json:"region"`
	City         string      `json:"city"`
	Timezone     string      `json:"timezone"`
	Language     string      `json:"language"`
	OccurredAt   time.Time   `json:"occurred_at"`
}

func (q *Queries) CreateAnalyticsPageview(ctx context.Context, arg CreateAnalyticsPageviewParams) error {
	_, err := q.db.Exec(ctx, createAnalyticsPageview,
		arg.SessionID,
		arg.VisitorID,
		arg.Path,
		arg.Title,
		arg.Referrer,
		arg.ReferrerHost,
		arg.Channel,
		arg.Browser,
		arg.Os,
		arg.Device,
		arg.CountryCode,
		arg.Region,
		arg.City,
		arg.Timezone,
		arg.Language,
		arg.OccurredAt,
	)
	return err
}

const getAnalyticsAverageVisitDurationSeconds = `-- name: GetAnalyticsAverageVisitDurationSeconds :one
SELECT coalesce(avg(EXTRACT(EPOCH FROM (last_seen_at - started_at))), 0)::double precision AS avg_seconds
FROM analytics_sessions
WHERE started_at >= $1 AND started_at < $2
`

type GetAnalyticsAverageVisitDurationSecondsParams struct {
	StartedAt   time.Time `json:"started_at"`
	StartedAt_2 time.Time `json:"started_at_2"`
}

func (q *Queries) GetAnalyticsAverageVisitDurationSeconds(ctx context.Context, arg GetAnalyticsAverageVisitDurationSecondsParams) (float64, error) {
	row := q.db.QueryRow(ctx, getAnalyticsAverageVisitDurationSeconds, arg.StartedAt, arg.StartedAt_2)
	var avg_seconds float64
	err := row.Scan(&avg_seconds)
	return avg_seconds, err
}

const getAnalyticsTrafficHeatmap = `-- name: GetAnalyticsTrafficHeatmap :many
SELECT
  extract(dow FROM occurred_at)::int AS dow,
  extract(hour FROM occurred_at)::int AS hour,
  count(*)::bigint AS value
FROM analytics_pageviews
WHERE occurred_at >= $1 AND occurred_at < $2
GROUP BY dow, hour
ORDER BY dow, hour
`

type GetAnalyticsTrafficHeatmapParams struct {
	OccurredAt   time.Time `json:"occurred_at"`
	OccurredAt_2 time.Time `json:"occurred_at_2"`
}

type GetAnalyticsTrafficHeatmapRow struct {
	Dow   int32 `json:"dow"`
	Hour  int32 `json:"hour"`
	Value int64 `json:"value"`
}

func (q *Queries) GetAnalyticsTrafficHeatmap(ctx context.Context, arg GetAnalyticsTrafficHeatmapParams) ([]GetAnalyticsTrafficHeatmapRow, error) {
	rows, err := q.db.Query(ctx, getAnalyticsTrafficHeatmap, arg.OccurredAt, arg.OccurredAt_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetAnalyticsTrafficHeatmapRow{}
	for rows.Next() {
		var i GetAnalyticsTrafficHeatmapRow
		if err := rows.Scan(&i.Dow, &i.Hour, &i.Value); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAnalyticsTrend = `-- name: GetAnalyticsTrend :many
SELECT
  CASE
    WHEN $3::text = 'hour' THEN to_char(date_trunc('hour', occurred_at), 'YYYY-MM-DD HH24:00')
    ELSE to_char(date_trunc('day', occurred_at), 'YYYY-MM-DD')
  END AS bucket,
  count(DISTINCT coalesce(visitor_id::text, session_id::text))::bigint AS visitors,
  count(*)::bigint AS views
FROM analytics_pageviews
WHERE occurred_at >= $1 AND occurred_at < $2
GROUP BY 1
ORDER BY 1
`

type GetAnalyticsTrendParams struct {
	OccurredAt   time.Time `json:"occurred_at"`
	OccurredAt_2 time.Time `json:"occurred_at_2"`
	Column3      string    `json:"column_3"`
}

type GetAnalyticsTrendRow struct {
	Bucket   interface{} `json:"bucket"`
	Visitors int64       `json:"visitors"`
	Views    int64       `json:"views"`
}

func (q *Queries) GetAnalyticsTrend(ctx context.Context, arg GetAnalyticsTrendParams) ([]GetAnalyticsTrendRow, error) {
	rows, err := q.db.Query(ctx, getAnalyticsTrend, arg.OccurredAt, arg.OccurredAt_2, arg.Column3)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetAnalyticsTrendRow{}
	for rows.Next() {
		var i GetAnalyticsTrendRow
		if err := rows.Scan(&i.Bucket, &i.Visitors, &i.Views); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAnalyticsBrowsers = `-- name: ListAnalyticsBrowsers :many
SELECT
  browser AS name,
  count(*)::bigint AS visitors
FROM analytics_sessions
WHERE started_at >= $1 AND started_at < $2
GROUP BY browser
ORDER BY visitors DESC, name ASC
LIMIT $3
`

type ListAnalyticsBrowsersParams struct {
	StartedAt   time.Time `json:"started_at"`
	StartedAt_2 time.Time `json:"started_at_2"`
	Limit       int32     `json:"limit"`
}

type ListAnalyticsBrowsersRow struct {
	Name     string `json:"name"`
	Visitors int64  `json:"visitors"`
}

func (q *Queries) ListAnalyticsBrowsers(ctx context.Context, arg ListAnalyticsBrowsersParams) ([]ListAnalyticsBrowsersRow, error) {
	rows, err := q.db.Query(ctx, listAnalyticsBrowsers, arg.StartedAt, arg.StartedAt_2, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAnalyticsBrowsersRow{}
	for rows.Next() {
		var i ListAnalyticsBrowsersRow
		if err := rows.Scan(&i.Name, &i.Visitors); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAnalyticsChannels = `-- name: ListAnalyticsChannels :many
SELECT
  channel AS name,
  count(*)::bigint AS visitors
FROM analytics_sessions
WHERE started_at >= $1 AND started_at < $2
GROUP BY channel
ORDER BY visitors DESC, name ASC
LIMIT $3
`

type ListAnalyticsChannelsParams struct {
	StartedAt   time.Time `json:"started_at"`
	StartedAt_2 time.Time `json:"started_at_2"`
	Limit       int32     `json:"limit"`
}

type ListAnalyticsChannelsRow struct {
	Name     string `json:"name"`
	Visitors int64  `json:"visitors"`
}

func (q *Queries) ListAnalyticsChannels(ctx context.Context, arg ListAnalyticsChannelsParams) ([]ListAnalyticsChannelsRow, error) {
	rows, err := q.db.Query(ctx, listAnalyticsChannels, arg.StartedAt, arg.StartedAt_2, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAnalyticsChannelsRow{}
	for rows.Next() {
		var i ListAnalyticsChannelsRow
		if err := rows.Scan(&i.Name, &i.Visitors); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAnalyticsCities = `-- name: ListAnalyticsCities :many
SELECT
  city AS name,
  count(*)::bigint AS visitors
FROM analytics_sessions
WHERE started_at >= $1 AND started_at < $2
GROUP BY city
ORDER BY visitors DESC, name ASC
LIMIT $3
`

type ListAnalyticsCitiesParams struct {
	StartedAt   time.Time `json:"started_at"`
	StartedAt_2 time.Time `json:"started_at_2"`
	Limit       int32     `json:"limit"`
}

type ListAnalyticsCitiesRow struct {
	Name     string `json:"name"`
	Visitors int64  `json:"visitors"`
}

func (q *Queries) ListAnalyticsCities(ctx context.Context, arg ListAnalyticsCitiesParams) ([]ListAnalyticsCitiesRow, error) {
	rows, err := q.db.Query(ctx, listAnalyticsCities, arg.StartedAt, arg.StartedAt_2, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAnalyticsCitiesRow{}
	for rows.Next() {
		var i ListAnalyticsCitiesRow
		if err := rows.Scan(&i.Name, &i.Visitors); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAnalyticsCountries = `-- name: ListAnalyticsCountries :many
SELECT
  country_code,
  count(*)::bigint AS visitors
FROM analytics_sessions
WHERE started_at >= $1 AND started_at < $2
GROUP BY country_code
ORDER BY visitors DESC, country_code ASC
LIMIT $3
`

type ListAnalyticsCountriesParams struct {
	StartedAt   time.Time `json:"started_at"`
	StartedAt_2 time.Time `json:"started_at_2"`
	Limit       int32     `json:"limit"`
}

type ListAnalyticsCountriesRow struct {
	CountryCode string `json:"country_code"`
	Visitors    int64  `json:"visitors"`
}

func (q *Queries) ListAnalyticsCountries(ctx context.Context, arg ListAnalyticsCountriesParams) ([]ListAnalyticsCountriesRow, error) {
	rows, err := q.db.Query(ctx, listAnalyticsCountries, arg.StartedAt, arg.StartedAt_2, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAnalyticsCountriesRow{}
	for rows.Next() {
		var i ListAnalyticsCountriesRow
		if err := rows.Scan(&i.CountryCode, &i.Visitors); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAnalyticsDevices = `-- name: ListAnalyticsDevices :many
SELECT
  device AS name,
  count(*)::bigint AS visitors
FROM analytics_sessions
WHERE started_at >= $1 AND started_at < $2
GROUP BY device
ORDER BY visitors DESC, name ASC
LIMIT $3
`

type ListAnalyticsDevicesParams struct {
	StartedAt   time.Time `json:"started_at"`
	StartedAt_2 time.Time `json:"started_at_2"`
	Limit       int32     `json:"limit"`
}

type ListAnalyticsDevicesRow struct {
	Name     string `json:"name"`
	Visitors int64  `json:"visitors"`
}

func (q *Queries) ListAnalyticsDevices(ctx context.Context, arg ListAnalyticsDevicesParams) ([]ListAnalyticsDevicesRow, error) {
	rows, err := q.db.Query(ctx, listAnalyticsDevices, arg.StartedAt, arg.StartedAt_2, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAnalyticsDevicesRow{}
	for rows.Next() {
		var i ListAnalyticsDevicesRow
		if err := rows.Scan(&i.Name, &i.Visitors); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAnalyticsEntryPaths = `-- name: ListAnalyticsEntryPaths :many
SELECT
  entry_path AS path,
  count(*)::bigint AS visits
FROM analytics_sessions
WHERE started_at >= $1 AND started_at < $2
GROUP BY entry_path
ORDER BY visits DESC, path ASC
LIMIT $3
`

type ListAnalyticsEntryPathsParams struct {
	StartedAt   time.Time `json:"started_at"`
	StartedAt_2 time.Time `json:"started_at_2"`
	Limit       int32     `json:"limit"`
}

type ListAnalyticsEntryPathsRow struct {
	Path   string `json:"path"`
	Visits int64  `json:"visits"`
}

func (q *Queries) ListAnalyticsEntryPaths(ctx context.Context, arg ListAnalyticsEntryPathsParams) ([]ListAnalyticsEntryPathsRow, error) {
	rows, err := q.db.Query(ctx, listAnalyticsEntryPaths, arg.StartedAt, arg.StartedAt_2, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAnalyticsEntryPathsRow{}
	for rows.Next() {
		var i ListAnalyticsEntryPathsRow
		if err := rows.Scan(&i.Path, &i.Visits); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAnalyticsExitPaths = `-- name: ListAnalyticsExitPaths :many
SELECT
  exit_path AS path,
  count(*)::bigint AS visits
FROM analytics_sessions
WHERE started_at >= $1 AND started_at < $2
GROUP BY exit_path
ORDER BY visits DESC, path ASC
LIMIT $3
`

type ListAnalyticsExitPathsParams struct {
	StartedAt   time.Time `json:"started_at"`
	StartedAt_2 time.Time `json:"started_at_2"`
	Limit       int32     `json:"limit"`
}

type ListAnalyticsExitPathsRow struct {
	Path   string `json:"path"`
	Visits int64  `json:"visits"`
}

func (q *Queries) ListAnalyticsExitPaths(ctx context.Context, arg ListAnalyticsExitPathsParams) ([]ListAnalyticsExitPathsRow, error) {
	rows, err := q.db.Query(ctx, listAnalyticsExitPaths, arg.StartedAt, arg.StartedAt_2, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAnalyticsExitPathsRow{}
	for rows.Next() {
		var i ListAnalyticsExitPathsRow
		if err := rows.Scan(&i.Path, &i.Visits); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAnalyticsOperatingSystems = `-- name: ListAnalyticsOperatingSystems :many
SELECT
  os AS name,
  count(*)::bigint AS visitors
FROM analytics_sessions
WHERE started_at >= $1 AND started_at < $2
GROUP BY os
ORDER BY visitors DESC, name ASC
LIMIT $3
`

type ListAnalyticsOperatingSystemsParams struct {
	StartedAt   time.Time `json:"started_at"`
	StartedAt_2 time.Time `json:"started_at_2"`
	Limit       int32     `json:"limit"`
}

type ListAnalyticsOperatingSystemsRow struct {
	Name     string `json:"name"`
	Visitors int64  `json:"visitors"`
}

func (q *Queries) ListAnalyticsOperatingSystems(ctx context.Context, arg ListAnalyticsOperatingSystemsParams) ([]ListAnalyticsOperatingSystemsRow, error) {
	rows, err := q.db.Query(ctx, listAnalyticsOperatingSystems, arg.StartedAt, arg.StartedAt_2, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAnalyticsOperatingSystemsRow{}
	for rows.Next() {
		var i ListAnalyticsOperatingSystemsRow
		if err := rows.Scan(&i.Name, &i.Visitors); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAnalyticsPageStats = `-- name: ListAnalyticsPageStats :many
SELECT
  path,
  count(DISTINCT coalesce(visitor_id::text, session_id::text))::bigint AS visitors,
  count(*)::bigint AS views
FROM analytics_pageviews
WHERE occurred_at >= $1 AND occurred_at < $2
GROUP BY path
ORDER BY visitors DESC, views DESC, path ASC
LIMIT $3
`

type ListAnalyticsPageStatsParams struct {
	OccurredAt   time.Time `json:"occurred_at"`
	OccurredAt_2 time.Time `json:"occurred_at_2"`
	Limit        int32     `json:"limit"`
}

type ListAnalyticsPageStatsRow struct {
	Path     string `json:"path"`
	Visitors int64  `json:"visitors"`
	Views    int64  `json:"views"`
}

func (q *Queries) ListAnalyticsPageStats(ctx context.Context, arg ListAnalyticsPageStatsParams) ([]ListAnalyticsPageStatsRow, error) {
	rows, err := q.db.Query(ctx, listAnalyticsPageStats, arg.OccurredAt, arg.OccurredAt_2, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAnalyticsPageStatsRow{}
	for rows.Next() {
		var i ListAnalyticsPageStatsRow
		if err := rows.Scan(&i.Path, &i.Visitors, &i.Views); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAnalyticsReferrers = `-- name: ListAnalyticsReferrers :many
SELECT
  CASE WHEN referrer_host = '' THEN 'direct' ELSE referrer_host END AS name,
  count(*)::bigint AS visitors
FROM analytics_sessions
WHERE started_at >= $1 AND started_at < $2
GROUP BY 1
ORDER BY visitors DESC, name ASC
LIMIT $3
`

type ListAnalyticsReferrersParams struct {
	StartedAt   time.Time `json:"started_at"`
	StartedAt_2 time.Time `json:"started_at_2"`
	Limit       int32     `json:"limit"`
}

type ListAnalyticsReferrersRow struct {
	Name     interface{} `json:"name"`
	Visitors int64       `json:"visitors"`
}

func (q *Queries) ListAnalyticsReferrers(ctx context.Context, arg ListAnalyticsReferrersParams) ([]ListAnalyticsReferrersRow, error) {
	rows, err := q.db.Query(ctx, listAnalyticsReferrers, arg.StartedAt, arg.StartedAt_2, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAnalyticsReferrersRow{}
	for rows.Next() {
		var i ListAnalyticsReferrersRow
		if err := rows.Scan(&i.Name, &i.Visitors); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAnalyticsRegions = `-- name: ListAnalyticsRegions :many
SELECT
  region AS name,
  count(*)::bigint AS visitors
FROM analytics_sessions
WHERE started_at >= $1 AND started_at < $2
GROUP BY region
ORDER BY visitors DESC, name ASC
LIMIT $3
`

type ListAnalyticsRegionsParams struct {
	StartedAt   time.Time `json:"started_at"`
	StartedAt_2 time.Time `json:"started_at_2"`
	Limit       int32     `json:"limit"`
}

type ListAnalyticsRegionsRow struct {
	Name     string `json:"name"`
	Visitors int64  `json:"visitors"`
}

func (q *Queries) ListAnalyticsRegions(ctx context.Context, arg ListAnalyticsRegionsParams) ([]ListAnalyticsRegionsRow, error) {
	rows, err := q.db.Query(ctx, listAnalyticsRegions, arg.StartedAt, arg.StartedAt_2, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAnalyticsRegionsRow{}
	for rows.Next() {
		var i ListAnalyticsRegionsRow
		if err := rows.Scan(&i.Name, &i.Visitors); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertAnalyticsSession = `-- name: UpsertAnalyticsSession :one
INSERT INTO analytics_sessions (
    session_key,
    visitor_id,
    started_at,
    last_seen_at,
    entry_path,
    exit_path,
    referrer,
    referrer_host,
    channel,
    browser,
    os,
    device,
    country_code,
    region,
    city,
    timezone,
    language,
    pageviews
)
VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9,
    $10, $11, $12, $13, $14, $15, $16, $17, 1
)
ON CONFLICT (session_key) DO UPDATE
SET
    visitor_id = COALESCE(analytics_sessions.visitor_id, EXCLUDED.visitor_id),
    last_seen_at = GREATEST(analytics_sessions.last_seen_at, EXCLUDED.last_seen_at),
    exit_path = EXCLUDED.exit_path,
    referrer = CASE
        WHEN analytics_sessions.referrer = '' THEN EXCLUDED.referrer
        ELSE analytics_sessions.referrer
    END,
    referrer_host = CASE
        WHEN analytics_sessions.referrer_host = '' THEN EXCLUDED.referrer_host
        ELSE analytics_sessions.referrer_host
    END,
    channel = CASE
        WHEN analytics_sessions.channel IN ('', 'direct', 'unknown')
             AND EXCLUDED.channel NOT IN ('', 'direct', 'unknown') THEN EXCLUDED.channel
        ELSE analytics_sessions.channel
    END,
    browser = CASE
        WHEN analytics_sessions.browser = 'Unknown' AND EXCLUDED.browser != 'Unknown' THEN EXCLUDED.browser
        ELSE analytics_sessions.browser
    END,
    os = CASE
        WHEN analytics_sessions.os = 'Unknown' AND EXCLUDED.os != 'Unknown' THEN EXCLUDED.os
        ELSE analytics_sessions.os
    END,
    device = CASE
        WHEN analytics_sessions.device = 'Unknown' AND EXCLUDED.device != 'Unknown' THEN EXCLUDED.device
        ELSE analytics_sessions.device
    END,
    country_code = CASE
        WHEN analytics_sessions.country_code IN ('', 'ZZ') AND EXCLUDED.country_code NOT IN ('', 'ZZ') THEN EXCLUDED.country_code
        ELSE analytics_sessions.country_code
    END,
    region = CASE
        WHEN analytics_sessions.region = 'Unknown' AND EXCLUDED.region != 'Unknown' THEN EXCLUDED.region
        ELSE analytics_sessions.region
    END,
    city = CASE
        WHEN analytics_sessions.city = 'Unknown' AND EXCLUDED.city != 'Unknown' THEN EXCLUDED.city
        ELSE analytics_sessions.city
    END,
    timezone = CASE
        WHEN analytics_sessions.timezone = '' THEN EXCLUDED.timezone
        ELSE analytics_sessions.timezone
    END,
    language = CASE
        WHEN analytics_sessions.language = '' THEN EXCLUDED.language
        ELSE analytics_sessions.language
    END,
    pageviews = analytics_sessions.pageviews + 1,
    updated_at = now()
RETURNING id, started_at, last_seen_at, pageviews
`

type UpsertAnalyticsSessionParams struct {
	SessionKey   string      `json:"session_key"`
	VisitorID    pgtype.UUID `json:"visitor_id"`
	StartedAt    time.Time   `json:"started_at"`
	LastSeenAt   time.Time   `json:"last_seen_at"`
	EntryPath    string      `json:"entry_path"`
	ExitPath     string      `json:"exit_path"`
	Referrer     string      `json:"referrer"`
	ReferrerHost string      `json:"referrer_host"`
	Channel      string      `json:"channel"`
	Browser      string      `json:"browser"`
	Os           string      `json:"os"`
	Device       string      `json:"device"`
	CountryCode  string      `json:"country_code"`
	Region       string      `json:"region"`
	City         string      `json:"city"`
	Timezone     string      `json:"timezone"`
	Language     string      `json:"language"`
}

type UpsertAnalyticsSessionRow struct {
	ID         uuid.UUID `json:"id"`
	StartedAt  time.Time `json:"started_at"`
	LastSeenAt time.Time `json:"last_seen_at"`
	Pageviews  int32     `json:"pageviews"`
}

func (q *Queries) UpsertAnalyticsSession(ctx context.Context, arg UpsertAnalyticsSessionParams) (UpsertAnalyticsSessionRow, error) {
	row := q.db.QueryRow(ctx, upsertAnalyticsSession,
		arg.SessionKey,
		arg.VisitorID,
		arg.StartedAt,
		arg.LastSeenAt,
		arg.EntryPath,
		arg.ExitPath,
		arg.Referrer,
		arg.ReferrerHost,
		arg.Channel,
		arg.Browser,
		arg.Os,
		arg.Device,
		arg.CountryCode,
		arg.Region,
		arg.City,
		arg.Timezone,
		arg.Language,
	)
	var i UpsertAnalyticsSessionRow
	err := row.Scan(
		&i.ID,
		&i.StartedAt,
		&i.LastSeenAt,
		&i.Pageviews,
	)
	return i, err
}
