// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: guestbook.sql

package query

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countGuestbookMessages = `-- name: CountGuestbookMessages :one
SELECT count(*) FROM guestbook_messages WHERE status = 'approved' AND parent_id IS NULL
`

func (q *Queries) CountGuestbookMessages(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countGuestbookMessages)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createGuestbookMessage = `-- name: CreateGuestbookMessage :one
INSERT INTO guestbook_messages (parent_id, author_name, author_website, content, ip_hash, ua_hash)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, created_at
`

type CreateGuestbookMessageParams struct {
	ParentID      pgtype.UUID `json:"parent_id"`
	AuthorName    string      `json:"author_name"`
	AuthorWebsite string      `json:"author_website"`
	Content       string      `json:"content"`
	IpHash        string      `json:"ip_hash"`
	UaHash        string      `json:"ua_hash"`
}

type CreateGuestbookMessageRow struct {
	ID        uuid.UUID `json:"id"`
	CreatedAt time.Time `json:"created_at"`
}

func (q *Queries) CreateGuestbookMessage(ctx context.Context, arg CreateGuestbookMessageParams) (CreateGuestbookMessageRow, error) {
	row := q.db.QueryRow(ctx, createGuestbookMessage,
		arg.ParentID,
		arg.AuthorName,
		arg.AuthorWebsite,
		arg.Content,
		arg.IpHash,
		arg.UaHash,
	)
	var i CreateGuestbookMessageRow
	err := row.Scan(&i.ID, &i.CreatedAt)
	return i, err
}

const deleteGuestbookVote = `-- name: DeleteGuestbookVote :exec
DELETE FROM guestbook_votes WHERE message_id = $1 AND visitor_id = $2
`

type DeleteGuestbookVoteParams struct {
	MessageID uuid.UUID `json:"message_id"`
	VisitorID uuid.UUID `json:"visitor_id"`
}

func (q *Queries) DeleteGuestbookVote(ctx context.Context, arg DeleteGuestbookVoteParams) error {
	_, err := q.db.Exec(ctx, deleteGuestbookVote, arg.MessageID, arg.VisitorID)
	return err
}

const getGuestbookVote = `-- name: GetGuestbookVote :one
SELECT vote FROM guestbook_votes
WHERE message_id = $1 AND visitor_id = $2
`

type GetGuestbookVoteParams struct {
	MessageID uuid.UUID `json:"message_id"`
	VisitorID uuid.UUID `json:"visitor_id"`
}

func (q *Queries) GetGuestbookVote(ctx context.Context, arg GetGuestbookVoteParams) (VoteType, error) {
	row := q.db.QueryRow(ctx, getGuestbookVote, arg.MessageID, arg.VisitorID)
	var vote VoteType
	err := row.Scan(&vote)
	return vote, err
}

const getVisitorVotesForMessages = `-- name: GetVisitorVotesForMessages :many
SELECT message_id, vote
FROM guestbook_votes
WHERE visitor_id = $1 AND message_id = ANY($2::uuid[])
`

type GetVisitorVotesForMessagesParams struct {
	VisitorID uuid.UUID   `json:"visitor_id"`
	Column2   []uuid.UUID `json:"column_2"`
}

type GetVisitorVotesForMessagesRow struct {
	MessageID uuid.UUID `json:"message_id"`
	Vote      VoteType  `json:"vote"`
}

func (q *Queries) GetVisitorVotesForMessages(ctx context.Context, arg GetVisitorVotesForMessagesParams) ([]GetVisitorVotesForMessagesRow, error) {
	rows, err := q.db.Query(ctx, getVisitorVotesForMessages, arg.VisitorID, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetVisitorVotesForMessagesRow{}
	for rows.Next() {
		var i GetVisitorVotesForMessagesRow
		if err := rows.Scan(&i.MessageID, &i.Vote); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGuestbookMessages = `-- name: ListGuestbookMessages :many
SELECT m.id, m.parent_id, m.author_name, m.author_website, m.content,
       m.vote_score, m.created_at
FROM guestbook_messages m
WHERE m.status = 'approved' AND m.parent_id IS NULL
ORDER BY
    CASE WHEN $3::text = 'hot' THEN m.vote_score END DESC,
    CASE WHEN $3::text = 'oldest' THEN m.created_at END ASC,
    CASE WHEN $3::text = 'newest' OR $3::text NOT IN ('hot','oldest') THEN m.created_at END DESC
LIMIT $1 OFFSET $2
`

type ListGuestbookMessagesParams struct {
	Limit  int32  `json:"limit"`
	Offset int32  `json:"offset"`
	SortBy string `json:"sort_by"`
}

type ListGuestbookMessagesRow struct {
	ID            uuid.UUID   `json:"id"`
	ParentID      pgtype.UUID `json:"parent_id"`
	AuthorName    string      `json:"author_name"`
	AuthorWebsite string      `json:"author_website"`
	Content       string      `json:"content"`
	VoteScore     int32       `json:"vote_score"`
	CreatedAt     time.Time   `json:"created_at"`
}

func (q *Queries) ListGuestbookMessages(ctx context.Context, arg ListGuestbookMessagesParams) ([]ListGuestbookMessagesRow, error) {
	rows, err := q.db.Query(ctx, listGuestbookMessages, arg.Limit, arg.Offset, arg.SortBy)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListGuestbookMessagesRow{}
	for rows.Next() {
		var i ListGuestbookMessagesRow
		if err := rows.Scan(
			&i.ID,
			&i.ParentID,
			&i.AuthorName,
			&i.AuthorWebsite,
			&i.Content,
			&i.VoteScore,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGuestbookReplies = `-- name: ListGuestbookReplies :many
SELECT id, parent_id, author_name, author_website, content, vote_score, created_at
FROM guestbook_messages
WHERE parent_id = $1 AND status = 'approved'
ORDER BY created_at ASC
`

type ListGuestbookRepliesRow struct {
	ID            uuid.UUID   `json:"id"`
	ParentID      pgtype.UUID `json:"parent_id"`
	AuthorName    string      `json:"author_name"`
	AuthorWebsite string      `json:"author_website"`
	Content       string      `json:"content"`
	VoteScore     int32       `json:"vote_score"`
	CreatedAt     time.Time   `json:"created_at"`
}

func (q *Queries) ListGuestbookReplies(ctx context.Context, parentID pgtype.UUID) ([]ListGuestbookRepliesRow, error) {
	rows, err := q.db.Query(ctx, listGuestbookReplies, parentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListGuestbookRepliesRow{}
	for rows.Next() {
		var i ListGuestbookRepliesRow
		if err := rows.Scan(
			&i.ID,
			&i.ParentID,
			&i.AuthorName,
			&i.AuthorWebsite,
			&i.Content,
			&i.VoteScore,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recalcGuestbookVoteScore = `-- name: RecalcGuestbookVoteScore :exec
UPDATE guestbook_messages
SET vote_score = (
    SELECT coalesce(sum(CASE WHEN vote = 'up' THEN 1 ELSE -1 END), 0)
    FROM guestbook_votes WHERE message_id = $1
)
WHERE id = $1
`

func (q *Queries) RecalcGuestbookVoteScore(ctx context.Context, messageID uuid.UUID) error {
	_, err := q.db.Exec(ctx, recalcGuestbookVoteScore, messageID)
	return err
}

const upsertGuestbookVote = `-- name: UpsertGuestbookVote :exec
INSERT INTO guestbook_votes (message_id, visitor_id, vote)
VALUES ($1, $2, $3)
ON CONFLICT (message_id, visitor_id) DO UPDATE
SET vote = EXCLUDED.vote, updated_at = now()
`

type UpsertGuestbookVoteParams struct {
	MessageID uuid.UUID `json:"message_id"`
	VisitorID uuid.UUID `json:"visitor_id"`
	Vote      VoteType  `json:"vote"`
}

func (q *Queries) UpsertGuestbookVote(ctx context.Context, arg UpsertGuestbookVoteParams) error {
	_, err := q.db.Exec(ctx, upsertGuestbookVote, arg.MessageID, arg.VisitorID, arg.Vote)
	return err
}
