// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: moderation.sql

package query

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const checkBlockedIP = `-- name: CheckBlockedIP :one
SELECT count(*) FROM blocked_ips
WHERE ip_hash = $1 AND (expires_at IS NULL OR expires_at > now())
`

func (q *Queries) CheckBlockedIP(ctx context.Context, ipHash string) (int64, error) {
	row := q.db.QueryRow(ctx, checkBlockedIP, ipHash)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAuditLog = `-- name: CreateAuditLog :exec
INSERT INTO audit_logs (admin_id, action, target_type, target_id, detail, ip)
VALUES ($1, $2, $3, $4, $5, $6)
`

type CreateAuditLogParams struct {
	AdminID    pgtype.UUID     `json:"admin_id"`
	Action     string          `json:"action"`
	TargetType string          `json:"target_type"`
	TargetID   string          `json:"target_id"`
	Detail     json.RawMessage `json:"detail"`
	Ip         string          `json:"ip"`
}

func (q *Queries) CreateAuditLog(ctx context.Context, arg CreateAuditLogParams) error {
	_, err := q.db.Exec(ctx, createAuditLog,
		arg.AdminID,
		arg.Action,
		arg.TargetType,
		arg.TargetID,
		arg.Detail,
		arg.Ip,
	)
	return err
}

const listAuditLogs = `-- name: ListAuditLogs :many
SELECT a.id, a.action, a.target_type, a.target_id, a.detail, a.ip, a.created_at,
       u.username AS admin_username
FROM audit_logs a
LEFT JOIN admin_users u ON u.id = a.admin_id
ORDER BY a.created_at DESC
LIMIT $1 OFFSET $2
`

type ListAuditLogsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type ListAuditLogsRow struct {
	ID            uuid.UUID       `json:"id"`
	Action        string          `json:"action"`
	TargetType    string          `json:"target_type"`
	TargetID      string          `json:"target_id"`
	Detail        json.RawMessage `json:"detail"`
	Ip            string          `json:"ip"`
	CreatedAt     time.Time       `json:"created_at"`
	AdminUsername pgtype.Text     `json:"admin_username"`
}

func (q *Queries) ListAuditLogs(ctx context.Context, arg ListAuditLogsParams) ([]ListAuditLogsRow, error) {
	rows, err := q.db.Query(ctx, listAuditLogs, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAuditLogsRow{}
	for rows.Next() {
		var i ListAuditLogsRow
		if err := rows.Scan(
			&i.ID,
			&i.Action,
			&i.TargetType,
			&i.TargetID,
			&i.Detail,
			&i.Ip,
			&i.CreatedAt,
			&i.AdminUsername,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSensitiveWords = `-- name: ListSensitiveWords :many
SELECT word FROM sensitive_words ORDER BY word
`

func (q *Queries) ListSensitiveWords(ctx context.Context) ([]string, error) {
	rows, err := q.db.Query(ctx, listSensitiveWords)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var word string
		if err := rows.Scan(&word); err != nil {
			return nil, err
		}
		items = append(items, word)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
