// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: post_comments.sql

package query

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const approveComment = `-- name: ApproveComment :exec
UPDATE post_comments
SET status = 'approved', approved_at = now(), reviewed_by = $2
WHERE id = $1
`

type ApproveCommentParams struct {
	ID         uuid.UUID   `json:"id"`
	ReviewedBy pgtype.UUID `json:"reviewed_by"`
}

func (q *Queries) ApproveComment(ctx context.Context, arg ApproveCommentParams) error {
	_, err := q.db.Exec(ctx, approveComment, arg.ID, arg.ReviewedBy)
	return err
}

const countAdminComments = `-- name: CountAdminComments :one
SELECT count(*)
FROM post_comments
WHERE ($1::moderation_status IS NULL OR status = $1::moderation_status)
`

func (q *Queries) CountAdminComments(ctx context.Context, status NullModerationStatus) (int64, error) {
	row := q.db.QueryRow(ctx, countAdminComments, status)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countApprovedComments = `-- name: CountApprovedComments :one
SELECT count(*) FROM post_comments WHERE post_id = $1 AND status = 'approved'
`

func (q *Queries) CountApprovedComments(ctx context.Context, postID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countApprovedComments, postID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countPendingComments = `-- name: CountPendingComments :one
SELECT count(*) FROM post_comments WHERE status = 'pending'
`

func (q *Queries) CountPendingComments(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countPendingComments)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createPostComment = `-- name: CreatePostComment :one
INSERT INTO post_comments (post_id, parent_id, author_name, author_email, author_website, content, ip_hash, ua_hash)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, created_at
`

type CreatePostCommentParams struct {
	PostID        uuid.UUID   `json:"post_id"`
	ParentID      pgtype.UUID `json:"parent_id"`
	AuthorName    string      `json:"author_name"`
	AuthorEmail   string      `json:"author_email"`
	AuthorWebsite string      `json:"author_website"`
	Content       string      `json:"content"`
	IpHash        string      `json:"ip_hash"`
	UaHash        string      `json:"ua_hash"`
}

type CreatePostCommentRow struct {
	ID        uuid.UUID `json:"id"`
	CreatedAt time.Time `json:"created_at"`
}

func (q *Queries) CreatePostComment(ctx context.Context, arg CreatePostCommentParams) (CreatePostCommentRow, error) {
	row := q.db.QueryRow(ctx, createPostComment,
		arg.PostID,
		arg.ParentID,
		arg.AuthorName,
		arg.AuthorEmail,
		arg.AuthorWebsite,
		arg.Content,
		arg.IpHash,
		arg.UaHash,
	)
	var i CreatePostCommentRow
	err := row.Scan(&i.ID, &i.CreatedAt)
	return i, err
}

const deleteComment = `-- name: DeleteComment :exec
DELETE FROM post_comments WHERE id = $1
`

func (q *Queries) DeleteComment(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteComment, id)
	return err
}

const listAdminComments = `-- name: ListAdminComments :many
SELECT c.id, c.post_id, c.parent_id, c.author_name, c.author_email,
       c.content, c.status, c.ip_hash, c.created_at,
       p.title AS post_title
FROM post_comments c
LEFT JOIN posts p ON p.id = c.post_id
WHERE ($3::moderation_status IS NULL OR c.status = $3::moderation_status)
ORDER BY c.created_at DESC
LIMIT $1 OFFSET $2
`

type ListAdminCommentsParams struct {
	Limit  int32                `json:"limit"`
	Offset int32                `json:"offset"`
	Status NullModerationStatus `json:"status"`
}

type ListAdminCommentsRow struct {
	ID          uuid.UUID        `json:"id"`
	PostID      uuid.UUID        `json:"post_id"`
	ParentID    pgtype.UUID      `json:"parent_id"`
	AuthorName  string           `json:"author_name"`
	AuthorEmail string           `json:"author_email"`
	Content     string           `json:"content"`
	Status      ModerationStatus `json:"status"`
	IpHash      string           `json:"ip_hash"`
	CreatedAt   time.Time        `json:"created_at"`
	PostTitle   pgtype.Text      `json:"post_title"`
}

func (q *Queries) ListAdminComments(ctx context.Context, arg ListAdminCommentsParams) ([]ListAdminCommentsRow, error) {
	rows, err := q.db.Query(ctx, listAdminComments, arg.Limit, arg.Offset, arg.Status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAdminCommentsRow{}
	for rows.Next() {
		var i ListAdminCommentsRow
		if err := rows.Scan(
			&i.ID,
			&i.PostID,
			&i.ParentID,
			&i.AuthorName,
			&i.AuthorEmail,
			&i.Content,
			&i.Status,
			&i.IpHash,
			&i.CreatedAt,
			&i.PostTitle,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listApprovedComments = `-- name: ListApprovedComments :many
SELECT id, post_id, parent_id, author_name, author_website, content,
       created_at
FROM post_comments
WHERE post_id = $1 AND status = 'approved'
ORDER BY created_at ASC
LIMIT $2 OFFSET $3
`

type ListApprovedCommentsParams struct {
	PostID uuid.UUID `json:"post_id"`
	Limit  int32     `json:"limit"`
	Offset int32     `json:"offset"`
}

type ListApprovedCommentsRow struct {
	ID            uuid.UUID   `json:"id"`
	PostID        uuid.UUID   `json:"post_id"`
	ParentID      pgtype.UUID `json:"parent_id"`
	AuthorName    string      `json:"author_name"`
	AuthorWebsite string      `json:"author_website"`
	Content       string      `json:"content"`
	CreatedAt     time.Time   `json:"created_at"`
}

func (q *Queries) ListApprovedComments(ctx context.Context, arg ListApprovedCommentsParams) ([]ListApprovedCommentsRow, error) {
	rows, err := q.db.Query(ctx, listApprovedComments, arg.PostID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListApprovedCommentsRow{}
	for rows.Next() {
		var i ListApprovedCommentsRow
		if err := rows.Scan(
			&i.ID,
			&i.PostID,
			&i.ParentID,
			&i.AuthorName,
			&i.AuthorWebsite,
			&i.Content,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const rejectComment = `-- name: RejectComment :exec
UPDATE post_comments
SET status = 'rejected', reviewed_by = $2
WHERE id = $1
`

type RejectCommentParams struct {
	ID         uuid.UUID   `json:"id"`
	ReviewedBy pgtype.UUID `json:"reviewed_by"`
}

func (q *Queries) RejectComment(ctx context.Context, arg RejectCommentParams) error {
	_, err := q.db.Exec(ctx, rejectComment, arg.ID, arg.ReviewedBy)
	return err
}
