// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: visitors.sql

package query

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createVisitor = `-- name: CreateVisitor :one
INSERT INTO visitors (ip_hash, ua_hash)
VALUES ($1, $2)
RETURNING id, first_seen_at
`

type CreateVisitorParams struct {
	IpHash string `json:"ip_hash"`
	UaHash string `json:"ua_hash"`
}

type CreateVisitorRow struct {
	ID          uuid.UUID `json:"id"`
	FirstSeenAt time.Time `json:"first_seen_at"`
}

func (q *Queries) CreateVisitor(ctx context.Context, arg CreateVisitorParams) (CreateVisitorRow, error) {
	row := q.db.QueryRow(ctx, createVisitor, arg.IpHash, arg.UaHash)
	var i CreateVisitorRow
	err := row.Scan(&i.ID, &i.FirstSeenAt)
	return i, err
}

const getVisitorByID = `-- name: GetVisitorByID :one
SELECT id, first_seen_at, last_seen_at, ip_hash, ua_hash
FROM visitors
WHERE id = $1
`

func (q *Queries) GetVisitorByID(ctx context.Context, id uuid.UUID) (Visitor, error) {
	row := q.db.QueryRow(ctx, getVisitorByID, id)
	var i Visitor
	err := row.Scan(
		&i.ID,
		&i.FirstSeenAt,
		&i.LastSeenAt,
		&i.IpHash,
		&i.UaHash,
	)
	return i, err
}

const getVisitorByIPUA = `-- name: GetVisitorByIPUA :one
SELECT id, first_seen_at, last_seen_at, ip_hash, ua_hash
FROM visitors
WHERE ip_hash = $1 AND ua_hash = $2
LIMIT 1
`

type GetVisitorByIPUAParams struct {
	IpHash string `json:"ip_hash"`
	UaHash string `json:"ua_hash"`
}

func (q *Queries) GetVisitorByIPUA(ctx context.Context, arg GetVisitorByIPUAParams) (Visitor, error) {
	row := q.db.QueryRow(ctx, getVisitorByIPUA, arg.IpHash, arg.UaHash)
	var i Visitor
	err := row.Scan(
		&i.ID,
		&i.FirstSeenAt,
		&i.LastSeenAt,
		&i.IpHash,
		&i.UaHash,
	)
	return i, err
}

const touchVisitor = `-- name: TouchVisitor :exec
UPDATE visitors SET last_seen_at = now() WHERE id = $1
`

func (q *Queries) TouchVisitor(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, touchVisitor, id)
	return err
}
